spring:
  profiles:
    active: local
  ##UTF-8 설정
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true
--- ## local 환경
# DB설정
spring: 
   profiles: local
   datasource:
    hikari:
     #username: carrot
     #password: ghavpdlwl1
     #jdbc-url: jdbc:log4jdbc:mariadb://49.247.213.177:23306/carrot_farm
     username: test
     password: pwd
     jdbc-url: jdbc:log4jdbc:mariadb://localhost:32773/kuder
     #jdbc-url : jdbc:mariadb://mxm.kr:23306/itest
     driver-class-name : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
     #jdbc-url: jdbc:log4jdbc:mariadb://mxm.kr:23306/itest
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
   #mvc:
    #view:
      #prefix: /WEB-INF/jsp
      #suffix: .jsp
     maximum-pool-size: 5
     auto-commit: false

spring.profiles.include: console-logging

--- ## 개발환경
spring:
  profiles: dev

#spring.profiles.include: console-logging, file-logging


